In [2]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [3]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


creating tensors

In [8]:
string = tf.Variable("hello world", tf.string)
number = tf.Variable(713, tf.int16)
floats = tf.Variable(77.7, tf.float64)

Rank/degree

In [10]:
rank1dim = tf.Variable(['cat', 'dog', 'bird'], tf.string)
rank2dim = tf.Variable([[1,2,3], [5,6,7]], tf.int16)

In [11]:
tf.rank(rank2dim)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [13]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [12]:
tf.rank(rank1dim)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
tf.shape(rank2dim)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

Change Shape

In [25]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [19]:
tensor = tf.ones([2,2,3])
print(tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [29]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]
print(matrix)
tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)
print(tensor)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>


In [41]:
three = tensor[0,2]  #3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  #first row
print(row1)

column1 = tensor[:, 0]  #first column
print(column1)

row_2_and_4 = tensor[0::2]  #second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5]
 [11 12 13 14 15]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


Evaluate tensors

In [47]:
tf.compat.v1.disable_eager_execution()
l = tf.constant(23, dtype="int32", name="val1")
m = tf.constant(25, dtype="int32", name="val2")
with tf.compat.v1.Session() as val:
  new_output = val.run(5*m)
  print(new_output)

125
